question_data = [
        {"category": "Science: Computers",
         "type": "boolean", "difficulty": "medium",
         "question": "FLAC stands for 'Free Lossless Audio Condenser'",
         "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
         "question": "The movie 'The Nightmare before Christmas' was all done with physical objects.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Sports", "type": "boolean", "difficulty": "medium",
         "question": "Skateboarding will be included in the 2020 Summer Olympics in Tokyo.",
         "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "Rebecca Chambers does not appear in any Resident Evil except for the original Resident Evil and the Gamecube remake.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
         "question": "'HTML' stands for Hypertext Markup Language.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
         "question": "For his performance at ComplexCon 2016 in Long Beach, California, Skrillex revived his 'Mothership' set piece for one night only.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
         "question": "Mortal Kombat was almost based on Jean-Claude Van Damme movie.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
         "question": "The majority of Subaru vehicles are made in China.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "History", "type": "boolean", "difficulty": "hard",
         "question": "The man that shot Alexander Hamilton was named Aaron Burr.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "In Resident Evil 4, the Chicago Typewriter has infinite ammo.", "correct_answer": "True",
         "incorrect_answers": ["False"]}
    ]
